### PR TITLE
no license options for tools create

### PR DESCRIPTION
**Pull request by sxren**
Sub-issue from #142.

The licenses select dropdown at `tools/create` contains no options.

### CODE REVIEW

**Comment by rgrp** [comment]
@sxren i wonder if we want to be more selective re our list of licenses (where did you pull these from). Also what do you think about patching upstream vs here (very happy to take this direct patch now to get stuff moving).

**Comment by akuckartz** [comment]
Would be great to see that license info published as (Linked) Open Data.

**Comment by rgrp** [comment]
@akuckartz comments on the licenses as license data should go to https://github.com/okfn/licenses

**Comment by sxren** [comment]
@rgrp the data is from http://licenses.opendefinition.org/licenses/groups/od.json

can you clarify patching upstream?

**Comment by rgrp** [comment]
@sxren see the comment in #142 about the upstream repo for the creator being https://github.com/okfn/datapackage-init - though I note in this specific case if we are inlining the license data we probably want to do it here though we could do it into the datapackage-init repo (demo directory).

**Comment by sxren** [comment]
@rgrp gotcha! so only patch the view here. put the rest in datapackage-init.

**Comment by rgrp** [comment]
@sxren how are you doing on merging this upstream?

**Pull request closed without merging**
